name: steganography_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ninja
  - make
  - cmake
  - clang
  - doxygen
  - numpy
  - scipy
  - matplotlib       
  - boost=1.80.0   
  - pip 
  - pip:
    - breathe
    - sphinx
  - sdl2
  - glfw
  - imgui
  - libpng
  - libsndfile